<?php

namespace ContainerQJEuqDx;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WLwQe7jService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WLwQe7j' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WLwQe7j'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\RestauranteController::list' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\RestauranteController::list()', 'getRestauranteControllerlistService', true],
            'App\\Controller\\RestauranteController::show' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\RestauranteController::show()', 'getRestauranteControllershowService', true],
            'App\\Controller\\RestauranteController::create' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\RestauranteController::create()', 'getRestauranteControllercreateService', true],
            'App\\Controller\\RestauranteController::update' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\RestauranteController::update()', 'getRestauranteControllerupdateService', true],
            'App\\Controller\\RestauranteController::delete' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\RestauranteController::delete()', 'getRestauranteControllerdeleteService', true],
            'App\\Controller\\RestauranteController::exportarPDF' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\RestauranteController::exportarPDF()', 'getRestauranteControllerexportarPDFService', true],
            'App\\Controller\\UsuarioController::register' => ['privates', '.service_locator.3PbG7Du.App\\Controller\\UsuarioController::register()', 'getUsuarioControllerregisterService', true],
            'App\\Controller\\UsuarioController::login' => ['privates', '.service_locator.3PbG7Du.App\\Controller\\UsuarioController::login()', 'getUsuarioControllerloginService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\RestauranteController:list' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\RestauranteController::list()', 'getRestauranteControllerlistService', true],
            'App\\Controller\\RestauranteController:show' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\RestauranteController::show()', 'getRestauranteControllershowService', true],
            'App\\Controller\\RestauranteController:create' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\RestauranteController::create()', 'getRestauranteControllercreateService', true],
            'App\\Controller\\RestauranteController:update' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\RestauranteController::update()', 'getRestauranteControllerupdateService', true],
            'App\\Controller\\RestauranteController:delete' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\RestauranteController::delete()', 'getRestauranteControllerdeleteService', true],
            'App\\Controller\\RestauranteController:exportarPDF' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\RestauranteController::exportarPDF()', 'getRestauranteControllerexportarPDFService', true],
            'App\\Controller\\UsuarioController:register' => ['privates', '.service_locator.3PbG7Du.App\\Controller\\UsuarioController::register()', 'getUsuarioControllerregisterService', true],
            'App\\Controller\\UsuarioController:login' => ['privates', '.service_locator.3PbG7Du.App\\Controller\\UsuarioController::login()', 'getUsuarioControllerloginService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\RestauranteController::list' => '?',
            'App\\Controller\\RestauranteController::show' => '?',
            'App\\Controller\\RestauranteController::create' => '?',
            'App\\Controller\\RestauranteController::update' => '?',
            'App\\Controller\\RestauranteController::delete' => '?',
            'App\\Controller\\RestauranteController::exportarPDF' => '?',
            'App\\Controller\\UsuarioController::register' => '?',
            'App\\Controller\\UsuarioController::login' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\RestauranteController:list' => '?',
            'App\\Controller\\RestauranteController:show' => '?',
            'App\\Controller\\RestauranteController:create' => '?',
            'App\\Controller\\RestauranteController:update' => '?',
            'App\\Controller\\RestauranteController:delete' => '?',
            'App\\Controller\\RestauranteController:exportarPDF' => '?',
            'App\\Controller\\UsuarioController:register' => '?',
            'App\\Controller\\UsuarioController:login' => '?',
        ]);
    }
}
