<?php

namespace ContainerQJEuqDx;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUsuarioControllerloginService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3PbG7Du.App\Controller\UsuarioController::login()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3PbG7Du.App\\Controller\\UsuarioController::login()'] = ($container->privates['.service_locator.3PbG7Du'] ?? $container->load('get_ServiceLocator_3PbG7DuService'))->withContext('App\\Controller\\UsuarioController::login()', $container);
    }
}
