<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWkPOnsk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWkPOnsk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWkPOnsk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWkPOnsk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWkPOnsk\App_KernelDevDebugContainer([
    'container.build_hash' => 'WkPOnsk',
    'container.build_id' => '27352592',
    'container.build_time' => 1753743683,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWkPOnsk');
